
services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8000:80"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - php
networks:
    php:
        driver: bridge
